version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    volumes:
      - './docker/web/php.ini:/usr/local/etc/php/php.ini:ro'
      - '.:/srv/app:rw,cached'
    depends_on:
      - db
      - mailhog
  nginx:
    image: nginx
    ports:
      - '8181:80'
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - '.:/srv/app/'
    depends_on:
      - web
  db:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    ports:
      - '8585:80'